baseURL: "https://metiri.dk/"
languageCode: "en"
title: "Metiri Consult"
author: "Dr. Jesper Wittrup"

params:
  description: "Making justice systems efficient through data-driven solutions for courts and public sector institutions worldwide"
  author: "Dr. Jesper Wittrup"
  email: "jw@metiri.dk"
  phone: "(+45) 60897138"
  
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: "github"

# Since you're using custom layouts, you may not need the menu section
# Your navigation is handled directly in your HTML templates
# But keeping this for potential future use:
menu:
  main:
    - name: "Services"
      url: "/services/"
      weight: 1
    - name: "Publications"
      url: "/publications/"
      weight: 2
    - name: "Contact"
      url: "/contact/"
      weight: 3
    - name: "Login"
      url: "https://witjes.dk/login"
      weight: 4

outputs:
  home: ["HTML", "RSS"]
  page: ["HTML"]

# Enable emoji support
enableEmoji: true

# Ignore R-related files (important for blogdown)
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

# Pagination setting
paginate: 5

# Preserve taxonomy names
preserveTaxonomyNames: true