[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.112.0"
  HUGO_ENABLEGITINFO = "true"

[context.production]
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_ENV = "production"

[context.branch-deploy]
  command = "hugo --gc --minify -F -b $DEPLOY_PRIME_URL"

[context.deploy-preview]
  command = "hugo --gc --minify -F -b $DEPLOY_PRIME_URL"

# Optional: Add redirects if needed
# [[redirects]]
#   from = "/old-path/*"
#   to = "/new-path/:splat"
#   status = 301